# Generated by Django 4.0.4 on 2022-05-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30)),
                ('tipoMantenimiento', models.CharField(max_length=30)),
                ('EmpleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('EquipoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='equipo',
            field=models.ManyToManyField(through='empleado.Mantenimiento', to='equipo.equipo'),
        ),
    ]
